name: manage-azure-policy-940c1a87
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'initiatives/_Preview_RMIT_Malaysia_97a6d4f1-3bed-4cf4-ac5b-0e444c0408d6/**'
#      - .github/workflows/manage-azure-policy-940c1a87.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_940c1a87}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          initiatives/_Preview_RMIT_Malaysia_97a6d4f1-3bed-4cf4-ac5b-0e444c0408d6/**
